using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ciencia.OBJ
{
    [PetaPoco.PrimaryKey("Evol_Id_u")]
    public class Car_evol_u
    {
        public int Evol_Id_u { get; set; }
        public Nullable<double> Evol_Pac_Id_u { get; set; }
        public Nullable<int> Evol_Ingr_Id_u { get; set; }
        //public Nullable<System.DateTime> Evol_F { get; set; }
        public string Evol_Obs_u { get; set; }
        //public Nullable<short> Evol_Usr_Id_u { get; set; }
        public string Evol_Memo_u { get; set; }
        public string Evol_Cama_T_u { get; set; }
        public Nullable<System.DateTime> Evol_Cama_H_u { get; set; }
        public Nullable<short> Evol_Grpo_D_u { get; set; }
        public Nullable<short> Evol_Diag_D_u { get; set; }
        public Nullable<short> Evol_Timi_N_u { get; set; }
        public Nullable<short> Evol_Grace_N_u { get; set; }
        public Nullable<short> Evol_Crusade_N_u { get; set; }
        public Nullable<short> Evol_Asint_D_u { get; set; }
        public Nullable<short> Evol_TA_N_u { get; set; }
        public Nullable<short> Evol_TAc_N_u { get; set; }
        public Nullable<short> Evol_FC_N_u { get; set; }
        public Nullable<short> Evol_FR_N_u { get; set; }
        public Nullable<short> Evol_I_N_u { get; set; }
        public Nullable<short> Evol_E_N_u { get; set; }
        public Nullable<int> Evol_IE_N_u { get; set; }
        public Nullable<short> Evol_Sang_N_u { get; set; }
        public string Evol_Objetivo_T_u { get; set; }
        public Nullable<short> Evol_ECG_D_u { get; set; }
        public Nullable<short> Evol_ExF_D_u { get; set; }
        public Nullable<bool> Evol_Isq_B_u { get; set; }
        public Nullable<bool> Evol_Isq_InfartoConSST_B_u { get; set; }
        public Nullable<bool> Evol_Isq_InfartoSinSST_B_u { get; set; }
        public Nullable<bool> Evol_Isq_AnginaInestable_B_u { get; set; }
        public Nullable<bool> Evol_Isq_DiseccCoronaria_B_u { get; set; }
        public Nullable<bool> Evol_Isq_NoReflowCoronario_B_u { get; set; }
        public Nullable<bool> Evol_Isq_EmbolizacCoronaria_B_u { get; set; }
        public Nullable<bool> Evol_Isq_AnginaSecundaria_B_u { get; set; }
        public Nullable<bool> Evol_Isq_InfartoSecundario_B_u { get; set; }
        public Nullable<bool> Evol_Isq_TrobosisStent_B_u { get; set; }
        public Nullable<bool> Evol_Isq_VasoespasmoCoro_B_u { get; set; }
        public Nullable<bool> Evol_Isq_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Ins_B_u { get; set; }
        public Nullable<bool> Evol_Ins_InsufCardiologica_B_u { get; set; }
        public Nullable<bool> Evol_Ins_HipertensPulmonar_B_u { get; set; }
        public Nullable<bool> Evol_Ins_EdemaAgudoPulmon_B_u { get; set; }
        public Nullable<bool> Evol_Ins_BajoGastoCardiaco_B_u { get; set; }
        public Nullable<bool> Evol_Ins_FallaVD_B_u { get; set; }
        public Nullable<bool> Evol_Ins_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Hem_B_u { get; set; }
        public Nullable<bool> Evol_Hem_HipertensArterial_B_u { get; set; }
        public Nullable<bool> Evol_Hem_HipotensArterial_B_u { get; set; }
        public Nullable<bool> Evol_Hem_ShockCadiogenico_B_u { get; set; }
        public Nullable<bool> Evol_Hem_ShockSeptico_B_u { get; set; }
        public Nullable<bool> Evol_Hem_ShockHipovolemico_B_u { get; set; }
        public Nullable<bool> Evol_Hem_Ortostatismo_B_u { get; set; }
        public Nullable<bool> Evol_Hem_Vasoplejia_B_u { get; set; }
        public Nullable<bool> Evol_Hem_FallaMultiorganica_B_u { get; set; }
        public Nullable<bool> Evol_Hem_Hipovolemia_B_u { get; set; }
        public Nullable<bool> Evol_Hem_Otras_B_u { get; set; }
        public Nullable<bool> Evol_PQx_B_u { get; set; }
        public Nullable<bool> Evol_PQx_SangradoMedico_B_u { get; set; }
        public Nullable<bool> Evol_PQx_SangradoQx_B_u { get; set; }
        public Nullable<bool> Evol_PQx_RoturaEsternal_B_u { get; set; }
        public Nullable<bool> Evol_PQx_Hemotorax_B_u { get; set; }
        public Nullable<bool> Evol_PQx_Taponamiento_B_u { get; set; }
        public Nullable<bool> Evol_PQx_DehicencValvular_B_u { get; set; }
        public Nullable<bool> Evol_PQx_ObstrucionSubAo_B_u { get; set; }
        public Nullable<bool> Evol_PQx_ObstruccByPass_B_u { get; set; }
        public Nullable<bool> Evol_PQx_ReopNoSangrado_B_u { get; set; }
        public Nullable<bool> Evol_PQx_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Arritmias_B_u { get; set; }
        public Nullable<bool> Evol_Sup_B_u { get; set; }
        public Nullable<bool> Evol_Sup_FibrilacAuricular_B_u { get; set; }
        public Nullable<bool> Evol_Sup_AleteoAuricular_B_u { get; set; }
        public Nullable<bool> Evol_Sup_TPS_B_u { get; set; }
        public Nullable<bool> Evol_Sup_TaquicardAuricular_B_u { get; set; }
        public Nullable<bool> Evol_Sup_ExtrasistoliaAuricular_B_u { get; set; }
        public Nullable<bool> Evol_Sup_TaquicardiaSinusal_B_u { get; set; }
        public Nullable<bool> Evol_Sup_RitmoNodalActivo_B_u { get; set; }
        public Nullable<bool> Evol_Sup_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Ven_B_u { get; set; }
        public Nullable<bool> Evol_Ven_TaqVentricSostenida_B_u { get; set; }
        public Nullable<bool> Evol_Ven_TaqVentricNoSosten_B_u { get; set; }
        public Nullable<bool> Evol_Ven_FibrilacVentricular_B_u { get; set; }
        public Nullable<bool> Evol_Ven_RIVA_B_u { get; set; }
        public Nullable<bool> Evol_Ven_ExtrasistVentricular_B_u { get; set; }
        public Nullable<bool> Evol_Ven_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Bra_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BCRI_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BCRD_B_u { get; set; }
        public Nullable<bool> Evol_Bra_HBAI_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BAV1erGrado_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BAV2GradoMobitzI_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BAV2GradoMobitzII_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BAV3erGrado_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BAV2_u_B_u { get; set; }
        public Nullable<bool> Evol_Bra_BradicardiaSinusal_B_u { get; set; }
        public Nullable<bool> Evol_Bra_Otras_B_u { get; set; }
        public Nullable<bool> Evol_PCa_B_u { get; set; }
        public Nullable<bool> Evol_PCa_Asistolia_B_u { get; set; }
        public Nullable<bool> Evol_PCa_AESP_B_u { get; set; }
        public Nullable<bool> Evol_PCa_FV_TVsinPulso_B_u { get; set; }
        public Nullable<bool> Evol_PCa_Otros_B_u { get; set; }
        public Nullable<bool> Evol_Val_B_u { get; set; }
        public Nullable<bool> Evol_Val_InsufMiAguda_B_u { get; set; }
        public Nullable<bool> Evol_Val_InsufTrAguda_B_u { get; set; }
        public Nullable<bool> Evol_Val_InsufAoAguda_B_u { get; set; }
        public Nullable<bool> Evol_Val_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Mec_B_u { get; set; }
        public Nullable<bool> Evol_Mec_CIV_B_u { get; set; }
        public Nullable<bool> Evol_Mec_RoturaParedLibreVI_B_u { get; set; }
        public Nullable<bool> Evol_Mec_TaponamNoPostQx_B_u { get; set; }
        public Nullable<bool> Evol_Mec_RoturaCordalMI_B_u { get; set; }
        public Nullable<bool> Evol_Mec_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Per_B_u { get; set; }
        public Nullable<bool> Evol_Per_SindromeDressler_B_u { get; set; }
        public Nullable<bool> Evol_Per_Pericarditis_B_u { get; set; }
        public Nullable<bool> Evol_Per_PericardConstructiva_B_u { get; set; }
        public Nullable<bool> Evol_Per_DerramePericardTapon_B_u { get; set; }
        public Nullable<bool> Evol_Per_Taponamiento_B_u { get; set; }
        public Nullable<bool> Evol_Per_Otras_B_u { get; set; }
        public Nullable<bool> Evol_VPe_B_u { get; set; }
        public Nullable<bool> Evol_VPe_DiseccionAo_B_u { get; set; }
        public Nullable<bool> Evol_VPe_RoturaAoTorac_B_u { get; set; }
        public Nullable<bool> Evol_VPe_RoturaAoAbdom_B_u { get; set; }
        public Nullable<bool> Evol_VPe_HematoIntramural_B_u { get; set; }
        public Nullable<bool> Evol_VPe_IsquemiaAgMMII_B_u { get; set; }
        public Nullable<bool> Evol_VPe_OclusByPassMMII_B_u { get; set; }
        public Nullable<bool> Evol_VPe_OclusStentMMII_B_u { get; set; }
        public Nullable<bool> Evol_VPe_AmputacionMMII_B_u { get; set; }
        public Nullable<bool> Evol_VPe_SangrExtAccesoQx_B_u { get; set; }
        public Nullable<bool> Evol_VPe_HematAccesoQx_B_u { get; set; }
        public Nullable<bool> Evol_VPe_Pseudoaneurisma_B_u { get; set; }
        public Nullable<bool> Evol_VPe_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Inf_B_u { get; set; }
        public Nullable<bool> Evol_Inf_EndocarditisProtesica_B_u { get; set; }
        public Nullable<bool> Evol_Inf_EndocardNativaTricu_B_u { get; set; }
        public Nullable<bool> Evol_Inf_EndocardNativaAO_B_u { get; set; }
        public Nullable<bool> Evol_Inf_EndocardNativaMI_B_u { get; set; }
        public Nullable<bool> Evol_Inf_Mediastinitis_B_u { get; set; }
        public Nullable<bool> Evol_Inf_InfecBypassPerif_B_u { get; set; }
        public Nullable<bool> Evol_Inf_Otras_B_u { get; set; }
        public Nullable<bool> Evol_TnC_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TrombosVenosaMMII_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TrombosVenosaMMSS_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TrombosisPulmonar_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TrombosTerritArterial_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TrombosTerritVenoso_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TromboIntraVentrIzq_B_u { get; set; }
        public Nullable<bool> Evol_TnC_TromboOrejuelaIzq_B_u { get; set; }
        public Nullable<bool> Evol_TnC_Tromboflebitis_B_u { get; set; }
        public Nullable<bool> Evol_TnC_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_Neumonia_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_NeumoniaARM_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_FiebreNoFiliada_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_InfecAsocCateter_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_InfecUrinaria_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_HC_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_UC_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_Retrocultivo_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_PuntaCateter_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_PuncSubxifoidea_B_u { get; set; }
        public Nullable<bool> Evol_Ifc_Otras_B_u { get; set; }
        public string Evol_Ifc_T_u { get; set; }
        public Nullable<bool> Evol_Rsp_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_ReduccVolumPulm_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_DistressRespirat_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_Trali_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_Atelectasia_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_Neumotorax_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_DerrPeuralModSev_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_InsufRespNoEspecif_B_u { get; set; }
        public Nullable<bool> Evol_Rsp_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Nef_B_u { get; set; }
        public Nullable<bool> Evol_Nef_InsufRenalAgOligur_B_u { get; set; }
        public Nullable<bool> Evol_Nef_InsufRenalAgNoOligur_B_u { get; set; }
        public Nullable<bool> Evol_Nef_InsufRenalReagudiz_B_u { get; set; }
        public Nullable<bool> Evol_Nef_Hematuria_B_u { get; set; }
        public Nullable<bool> Evol_Nef_Hemodialisis_B_u { get; set; }
        public Nullable<bool> Evol_Nef_GloboVesical_B_u { get; set; }
        public Nullable<bool> Evol_Nef_Otras_B_u { get; set; }
        public Nullable<bool> Evol_MeI_B_u { get; set; }
        public Nullable<bool> Evol_MeI_AcidosRespirator_B_u { get; set; }
        public Nullable<bool> Evol_MeI_AcidosMetabolica_B_u { get; set; }
        public Nullable<bool> Evol_MeI_AlcalosisRepirator_B_u { get; set; }
        public Nullable<bool> Evol_MeI_AlcalosisMetabolica_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hiperkalemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipokalemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipercalcemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipocalcemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipomagnesemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipernatremia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hiponatremia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hiperglucemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Hipoglucemia_B_u { get; set; }
        public Nullable<bool> Evol_MeI_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Hematologico_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_TrombocitopInduc_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_Plaquetopenia_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_AnemiaConTransf_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_AnemiaSinTransf_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_CoagulopConSangr_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_CoagulopSinSangr_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_Leucopenia_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_Neutropenia_B_u { get; set; }
        public Nullable<bool> Evol_Hmt_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Sng_B_u { get; set; }
        public Nullable<bool> Evol_Sng_SangradoMayor_B_u { get; set; }
        public Nullable<bool> Evol_Sng_SangradoMenor_B_u { get; set; }
        public Nullable<bool> Evol_Sng_Otros_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_TransfGR_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_TransfPFC_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_TransfPlaq_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_Fibrinogeno_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_TransfCrioprecipit_B_u { get; set; }
        public Nullable<bool> Evol_Hmd_Otros_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_ACVisquemico_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_HemorragIntracran_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_AIT_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_ExitacPsicomotriz_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_DeterioroSensorio_B_u { get; set; }
        public Nullable<bool> Evol_Nrl_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Gas_B_u { get; set; }
        public Nullable<bool> Evol_Gas_AbdomenAgudo_B_u { get; set; }
        public Nullable<bool> Evol_Gas_SangrDigestAlto_B_u { get; set; }
        public Nullable<bool> Evol_Gas_SangrDigestBajo_B_u { get; set; }
        public Nullable<bool> Evol_Gas_DisfuncFallaHepat_B_u { get; set; }
        public Nullable<bool> Evol_Gas_Colestasis_B_u { get; set; }
        public Nullable<bool> Evol_Gas_Otras_B_u { get; set; }
        public Nullable<bool> Evol_Mdc_B_u { get; set; }
        public Nullable<bool> Evol_Mdc_IntoxicacOpioides_B_u { get; set; }
        public Nullable<bool> Evol_Mdc_Otras_B_u { get; set; }
        public Nullable<short> Evol_Area_D_u { get; set; }
        public string Evol_Pase_M_u { get; set; }
        public string Evol_Info_M_u { get; set; }
        public Nullable<short> Evol_SangSuma_N_u { get; set; }
        public Nullable<short> Evol_Peso_N_u { get; set; }
        public Nullable<short> Evol_PesoDif_N_u { get; set; }
        public Nullable<decimal> Evol_IE2_N_u { get; set; }

    }
}
