//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciencia.OBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_Partes
    {
        public int Parte_Id { get; set; }
        public Nullable<System.DateTime> Parte_DOp_Cir_F { get; set; }
        public string Parte_HC_T { get; set; }
        public string Parte_Edad_T { get; set; }
        public string Parte_Paciente_T { get; set; }
        public string Parte_T_Cir_T { get; set; }
        public string Parte_Ciruj_T { get; set; }
        public string Parte_Ayudante_T { get; set; }
        public string Parte_Instrumentador_T { get; set; }
        public string Parte_Anest_T { get; set; }
        public string Parte_Perfus_T { get; set; }
        public string Parte_Oxigen_T { get; set; }
        public Nullable<int> Parte_Oxigen_Name_N { get; set; }
        public Nullable<int> Parte_DOp_Cirugia_D { get; set; }
        public Nullable<int> Parte_Dop_TiemClampeo_N { get; set; }
        public Nullable<int> Parte_Dop_TiemNoS_Cec_N { get; set; }
        public Nullable<int> Parte_Dop_TiemCec_N { get; set; }
        public Nullable<int> Parte_Dop_TiemPielPiel_N { get; set; }
        public Nullable<int> Parte_DOp_CEC_D { get; set; }
        public string Parte_CD_Img_T { get; set; }
        public string Parte_Texto_1_T { get; set; }
        public string Parte_CirCor_MII { get; set; }
        public string Parte_CirCor_MID { get; set; }
        public Nullable<short> Parte_CirCor_MII_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_MII_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_MII_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_MII_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_MID_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_MID_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_MID_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_MID_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_Ao_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_Ao_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_Ao_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_Ao_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_Mi_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_Mi_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_Mi_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_Mi_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_Ve_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_Ve_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_Ve_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_Ve_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_Ot_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_Ot_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_Ot_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_Ot_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_V1_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_V1_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_V1_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_V1_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_V2_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_V2_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_V2_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_V2_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_V3_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_V3_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_V3_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_V3_CD_N { get; set; }
        public Nullable<short> Parte_CirCor_V4_DA_N { get; set; }
        public Nullable<short> Parte_CirCor_V4_DG_N { get; set; }
        public Nullable<short> Parte_CirCor_V4_CX_N { get; set; }
        public Nullable<short> Parte_CirCor_V4_CD_N { get; set; }
        public string Parte_LD_DA_T { get; set; }
        public string Parte_LD_CX_T { get; set; }
        public string Parte_LD_CX2_T { get; set; }
        public string Parte_LD_CD_T { get; set; }
        public string Parte_sCECInt_Shunt_DA_T { get; set; }
        public string Parte_sCECInt_Shunt_DA_N_T { get; set; }
        public string Parte_sCECInt_Shunt_DG_T { get; set; }
        public string Parte_sCECInt_Shunt_DG_N_T { get; set; }
        public string Parte_sCECInt_Shunt_CX_T { get; set; }
        public string Parte_sCECInt_Shunt_CX_N_T { get; set; }
        public string Parte_sCECInt_Shunt_CX2_T { get; set; }
        public string Parte_sCECInt_Shunt_CX2_N_T { get; set; }
        public string Parte_sCECInt_Shunt_CD_T { get; set; }
        public string Parte_sCECInt_Shunt_CD_N_T { get; set; }
        public string Parte_CirCor_LD_DA_T { get; set; }
        public string Parte_CirCor_LD_CX_T { get; set; }
        public string Parte_CirCor_LD_CX2_T { get; set; }
        public string Parte_CirCor_LD_CD_T { get; set; }
        public string Parte_Texto_2_T { get; set; }
        public string Parte_HCNumIng_T { get; set; }
        public Nullable<int> Parte_DOp_Id { get; set; }
        public Nullable<int> Parte_Est { get; set; }
        public Nullable<int> Parte_Usr { get; set; }
        public string Parte_Texto_3 { get; set; }
        public Nullable<int> Parte_DOp_MP_Electrof { get; set; }
        public string Parte_DOp_MP_TecnicoRadiol { get; set; }
        public string Parte_DOp_MP_Tecnico { get; set; }
        public Nullable<short> Parte_DOp_CellSaver_D { get; set; }
        public string Parte_CellSaver_T { get; set; }
        public Nullable<int> Parte_CIPNumInt_N { get; set; }
        public string Parte_CCCliDOp_Cir_HI_T { get; set; }
        public string Parte_CCCliDOp_Cir_HF_T { get; set; }
    }
}
